name: Python CI

on:
    push:
        branches:
            - main
        pull_request:
            branches:
                - main
jobs:
    test:
        runs_on: ubuntu-latest
        steps:
            - name:check out code
            uses: actions/checkout@v2
            with:
                python-version: "3.8"
        name: Install dependencies
        run: 
            python -m pip install --upgrade pip
            pip install -r requriments.txt

        - name: Run tests
        run: pytest
